"""resume_intelligence — master résumé, role branches, git-style versions, change log.

Four new tables (resume_branches, resume_versions, resume_changes, job_resume_analyses) plus
one column on applications (resume_version_id) linking a submitted application to the exact
structured version behind whatever file it used. See app/models/resume_intelligence.py for
why there is no separate "master résumé" or "role profile" table — both are represented by
existing tables (resume_versions with branch_id NULL, and resume_branches respectively).
resume_changes.version_id is nullable: a proposed-but-uncommitted change is attached to its
job_resume_analyses row via analysis_id instead, and gets a version_id once committed.
resume_version_id carries no DB-level ForeignKey — see app/models/application.py's own
comment on that column for why (SQLite migration-recreate compatibility).

Revision ID: 222bb0d3cd7e
Revises: c4d1e8f39a27
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '222bb0d3cd7e'
down_revision: Union[str, None] = 'c4d1e8f39a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('proposed', 'accepted', 'rejected', name='resume_change_status').create(op.get_bind())
    sa.Enum('added', 'removed', 'modified', 'reordered', 'rephrased', 'role_positioning', 'ats_alignment', 'market_signal', 'user_edit', 'ai_suggestion', 'restored', name='resume_change_type').create(op.get_bind())
    sa.Enum('initial', 'user_edit', 'ai_suggestion', 'restored', name='resume_version_source').create(op.get_bind())
    sa.Enum('product', 'engineering', 'architecture', 'data', name='role_family').create(op.get_bind())
    op.create_table('resume_branches',
    sa.Column('role_name', sa.String(length=200), nullable=False),
    sa.Column('role_family', postgresql.ENUM('product', 'engineering', 'architecture', 'data', name='role_family', create_type=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('market_signals', sa.JSON(), nullable=True),
    sa.Column('market_signals_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_branches', schema=None) as batch_op:
        batch_op.create_index('ix_resume_branch_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_branches_user_id'), ['user_id'], unique=False)

    op.create_table('resume_versions',
    sa.Column('branch_id', sa.String(length=32), nullable=True),
    sa.Column('parent_version_id', sa.String(length=32), nullable=True),
    sa.Column('version_label', sa.String(length=60), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source', postgresql.ENUM('initial', 'user_edit', 'ai_suggestion', 'restored', name='resume_version_source', create_type=False), nullable=False),
    sa.Column('commit_message', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['resume_branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['resume_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.create_index('ix_resume_version_parent', ['parent_version_id'], unique=False)
        batch_op.create_index('ix_resume_version_user_branch', ['user_id', 'branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_versions_user_id'), ['user_id'], unique=False)

    op.create_table('job_resume_analyses',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('branch_id', sa.String(length=32), nullable=False),
    sa.Column('base_version_id', sa.String(length=32), nullable=False),
    sa.Column('matched', sa.JSON(), nullable=False),
    sa.Column('partial', sa.JSON(), nullable=False),
    sa.Column('missing', sa.JSON(), nullable=False),
    sa.Column('unsupported', sa.JSON(), nullable=False),
    sa.Column('ats_alignment_pct', sa.Float(), nullable=True),
    sa.Column('role_fit_notes', sa.Text(), nullable=False),
    sa.Column('positioning_notes', sa.Text(), nullable=False),
    sa.Column('title_analysis', sa.JSON(), nullable=True),
    sa.Column('proposed_version_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['base_version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['resume_branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_version_id'], ['resume_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_resume_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_resume_analyses_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_job_resume_analysis_user_job', ['user_id', 'job_id'], unique=False)

    op.create_table('resume_changes',
    sa.Column('version_id', sa.String(length=32), nullable=True),
    sa.Column('analysis_id', sa.String(length=32), nullable=True),
    sa.Column('change_type', postgresql.ENUM('added', 'removed', 'modified', 'reordered', 'rephrased', 'role_positioning', 'ats_alignment', 'market_signal', 'user_edit', 'ai_suggestion', 'restored', name='resume_change_type', create_type=False), nullable=False),
    sa.Column('section', sa.String(length=60), nullable=False),
    sa.Column('before_text', sa.Text(), nullable=True),
    sa.Column('after_text', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_job_id', sa.String(length=32), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('proposed', 'accepted', 'rejected', name='resume_change_status', create_type=False), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['job_resume_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_changes', schema=None) as batch_op:
        batch_op.create_index('ix_resume_change_version', ['version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_changes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_version_id', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('resume_version_id')

    with op.batch_alter_table('resume_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_changes_user_id'))
        batch_op.drop_index('ix_resume_change_version')

    op.drop_table('resume_changes')
    with op.batch_alter_table('job_resume_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_job_resume_analysis_user_job')
        batch_op.drop_index(batch_op.f('ix_job_resume_analyses_user_id'))

    op.drop_table('job_resume_analyses')
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_versions_user_id'))
        batch_op.drop_index('ix_resume_version_user_branch')
        batch_op.drop_index('ix_resume_version_parent')

    op.drop_table('resume_versions')
    with op.batch_alter_table('resume_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_branches_user_id'))
        batch_op.drop_index('ix_resume_branch_user')

    op.drop_table('resume_branches')
    sa.Enum('product', 'engineering', 'architecture', 'data', name='role_family').drop(op.get_bind())
    sa.Enum('initial', 'user_edit', 'ai_suggestion', 'restored', name='resume_version_source').drop(op.get_bind())
    sa.Enum('added', 'removed', 'modified', 'reordered', 'rephrased', 'role_positioning', 'ats_alignment', 'market_signal', 'user_edit', 'ai_suggestion', 'restored', name='resume_change_type').drop(op.get_bind())
    sa.Enum('proposed', 'accepted', 'rejected', name='resume_change_status').drop(op.get_bind())
    # ### end Alembic commands ###
