"""job_os_core

NOT NULL columns carry a server_default so the migration succeeds against a database that
already holds applications and sessions; without one SQLite refuses the ALTER outright.

Revision ID: 08b65de44e8a
Revises: 0007
Create Date: 2026-08-13 12:23:09.417582+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '08b65de44e8a'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('doc_type', sa.Enum('cv', 'cover_letter', 'portfolio', 'certificate', 'work_sample', 'reference', 'other', name='document_type'), nullable=False),
    sa.Column('current_version_id', sa.String(length=32), nullable=True),
    sa.Column('source_resume_id', sa.String(length=32), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_document_user_type', ['user_id', 'doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    op.create_table('application_events',
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.Enum('discovered', 'shortlisted', 'cv_selected', 'cv_tailored', 'cover_letter_generated', 'application_started', 'application_paused', 'application_resumed', 'application_submitted', 'submission_verified', 'status_changed', 'recruiter_contacted', 'user_action_required', 'user_action_completed', 'assessment_invited', 'assessment_completed', 'interview_scheduled', 'follow_up_due', 'follow_up_sent', 'note_added', 'error', name='application_event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.create_index('ix_app_event_app_occurred', ['application_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_app_event_type', ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_events_user_id'), ['user_id'], unique=False)

    op.create_table('document_versions',
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_key_pdf', sa.String(length=500), nullable=True),
    sa.Column('storage_key_docx', sa.String(length=500), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('tailored_for_job_id', sa.String(length=32), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('created_reason', sa.String(length=120), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tailored_for_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_docver_document', ['document_id', 'version'], unique=True)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health', sa.Enum('healthy', 'needs_attention', 'blocked', 'stale', 'session_required', 'document_required', 'action_required', 'status_unknown', name='application_health'), nullable=False, server_default=sa.text('healthy')))
        batch_op.add_column(sa.Column('next_action', sa.Enum('respond_to_recruiter', 'complete_assessment', 'upload_cv', 'upload_document', 'relogin', 'complete_verification', 'confirm_application', 'review_answer', 'follow_up', 'schedule_interview', 'prepare_interview', 'review_application', 'verify_submission', 'resume_application', 'update_profile', 'wait', 'none', name='next_action'), nullable=False, server_default=sa.text('none')))
        batch_op.add_column(sa.Column('next_action_reason', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('next_action_priority', sa.Enum('high', 'medium', 'low', 'none', name='action_priority'), nullable=False, server_default=sa.text('none')))
        batch_op.add_column(sa.Column('next_action_score', sa.Float(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('action_due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('origin', sa.String(length=30), nullable=False, server_default=sa.text('discovery')))
        batch_op.add_column(sa.Column('portal', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('application_url', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('external_reference', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('resume_state', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('paused_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_activity_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('follow_up_due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assessment_due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assessment_url', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('interview_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('document_version_id', sa.String(length=32), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_job_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('first_seen_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_checked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('application_url', sa.String(length=2000), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_canonical_job_id'), ['canonical_job_id'], unique=False)

    with op.batch_alter_table('platform_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Enum('session_active', 'session_expiring', 'session_expired', 'auth_required', 'mfa_required', 'human_verification_required', 'server_blocked', 'interactive_available', 'automation_unsupported', 'not_connected', name='session_state'), nullable=False, server_default=sa.text('not_connected')))
        batch_op.add_column(sa.Column('last_used_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('state_detail', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('applications_tracked', sa.Integer(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_sessions', schema=None) as batch_op:
        batch_op.drop_column('applications_tracked')
        batch_op.drop_column('state_detail')
        batch_op.drop_column('last_used_at')
        batch_op.drop_column('state')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_canonical_job_id'))
        batch_op.drop_column('application_url')
        batch_op.drop_column('last_checked_at')
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('first_seen_at')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('canonical_job_id')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('document_version_id')
        batch_op.drop_column('interview_at')
        batch_op.drop_column('assessment_url')
        batch_op.drop_column('assessment_due_at')
        batch_op.drop_column('follow_up_due_at')
        batch_op.drop_column('last_activity_at')
        batch_op.drop_column('paused_at')
        batch_op.drop_column('resume_state')
        batch_op.drop_column('external_reference')
        batch_op.drop_column('application_url')
        batch_op.drop_column('portal')
        batch_op.drop_column('origin')
        batch_op.drop_column('action_due_at')
        batch_op.drop_column('next_action_score')
        batch_op.drop_column('next_action_priority')
        batch_op.drop_column('next_action_reason')
        batch_op.drop_column('next_action')
        batch_op.drop_column('health')

    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_docver_document')
        batch_op.drop_index(batch_op.f('ix_document_versions_user_id'))

    op.drop_table('document_versions')
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_events_user_id'))
        batch_op.drop_index('ix_app_event_type')
        batch_op.drop_index('ix_app_event_app_occurred')

    op.drop_table('application_events')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_index('ix_document_user_type')

    op.drop_table('documents')
    # ### end Alembic commands ###
